name: flutter_http_local_server
description: A flutter mobile server example.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0-238.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
